source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

gem "rails", "~> 7.0.8", ">= 7.0.8.1"

# アクティブレコードのデータベースとしてpostgresqlを使用
gem "pg", "~> 1.1"

gem "puma", "~> 5.0"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

group :development, :test do
  #psyコンソールを使用出来るようにする
  gem "pry-byebug"
  gem "pry-rails"
  gem "pry-doc"

end
