source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

gem "rails", "~> 7.0.8", ">= 7.0.8.1"

# アクティブレコードのデータベースとしてpostgresqlを使用
gem "pg", "~> 1.1"

gem "puma", "~> 5.0"

# cors設定用
gem "rack-cors"

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "bootsnap", require: false

# 環境毎の設定を管理
gem "config"

# ユーザー認証
gem "devise"
gem "devise-i18n"
gem "devise_token_auth"

group :development, :test do
  gem "letter_opener_web"

  # psyコンソールを使用出来るようにする
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # テストフレームワーク
  gem "rspec-rails"

  # rubocop
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
